In [3]:
import numpy as np
import pylab as pl
import warnings

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings("ignore")

## Уровень 0

Придумайте матрицы, которые обладают следующими свойствами:  
a) диагональная, ортогональная, но не единичная(!):  
b) верхнетреугольная, ортогональная:  
c) нижнетреугольная, ортогональная:  
d) матрица, у которой определитель = 1, и все элементы не равны 0:  
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:  
m = np.array([[2, 2],  
[1, 3]])  
print(m)

***Решение***

In [80]:
m = np.array([[2, 2], [1, 3]])  
zn, vec = linalg.eigh(m)
print(zn)
print(vec)

[1.38196601 3.61803399]
[[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]


In [84]:
#диагональная, ортогональная, но не единичная
diag_otro = np.diag([3, 4, 8])
diag_otro.T

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [87]:
#верхнетреугольная, ортогональная
low_orto = np.tril([[1, 2, 3, 4], [4, 8, 2, 3], [3, 7, 1, 2], [2, 3, 4, 3]])
low_orto.T

array([[1, 4, 3, 2],
       [0, 8, 7, 3],
       [0, 0, 1, 4],
       [0, 0, 0, 3]])

In [88]:
#нижнетреугольная, ортогональная
up_orto = np.triu([[1, 2, 3, 4], [4, 8, 2, 3], [3, 7, 1, 2], [2, 3, 4, 3]])
up_orto.T

array([[1, 0, 0, 0],
       [2, 8, 0, 0],
       [3, 2, 1, 0],
       [4, 3, 2, 3]])

In [64]:
#матрица, у которой определитель = 1, и все элементы не равны 0
a = np.array([[1, 2, 1], [2, 3, 6], [1, 1, 4]])
det = np.linalg.det(a)

det

1.0

## Уровень 1

Найдите спектральное разложение матрицы:  
m = np.array([[1, 2],  
[2,3]])  

In [104]:
m = np.array([[1, 2], 
              [2,3]])  
print(m)

[[1 2]
 [2 3]]


In [105]:
v, w = np.linalg.eigh(m)

In [106]:
#получили собственные значения
v

array([-0.23606798,  4.23606798])

In [107]:
#получили матрицу собственных векторов
w

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [108]:
#диагональная матрица у которой на диагонали находятся собственные значения исходной матрицы
D = np.diag(v)
D

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [109]:
#две ортогональные относительно друг друга матрицы, состоящие из собственных векторов
S = w.T
S

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [110]:
#транспонированная форма матрицы S
S.T

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [112]:
#проверяем ортогональны ли матрицы S транспонированная и S
np.dot(S.T, S)

array([[ 1.0000000e+00, -1.2127222e-17],
       [-1.2127222e-17,  1.0000000e+00]])

In [113]:
#проверяем действительно ли матрицы S.T, S и D образуют спектральное разложение
np.dot((np.dot(S.T, D)), S)

array([[1., 2.],
       [2., 3.]])